greymatter-io/helm-charts

- ci/Jenkinsfile
change the ci process to only publish release branches to Nexus.  We will no longer push master branch
<br/><br/>
None
<br/><br/>
n/a
<br/><br/>
n/a
<br/><br/>
> update jenkinsfile to only push on release branches

- greymatter/Chart.yaml
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
> remove -dev tag

- docs/Getting Started.md
I updated the Getting Started doc to be more explicit about installing from the hosted Nexus repo. I made a lot of other improvements.
n/a
n/a
n/a
> 2.0 update docs

- greymatter-custom.yaml
- greymatter/README.md
- greymatter/requirements-dev.yaml
- greymatter/requirements-gov-dev.yaml
- greymatter/requirements.yaml
- slo/Chart.yaml
- slo/templates/postgres-certs.yaml
- slo/templates/postgres-slo-config.yaml
- slo/templates/postgres-slo-overrides.yaml
- slo/templates/postgres.yaml
- slo/templates/slo.yaml
- slo/values.yaml
This is a back merge of https://github.com/DecipherNow/helm-charts/pull/256 from release-2.0.
> Merging PR256 from release-2.0

- catalog/values.yaml
- control/values.yaml
- edge/templates/edge-ingress.yaml
- gm-control-api/values.yaml
- greymatter-custom-mesh-2.yaml
- greymatter/requirements.yaml
- greymatter/requirements.yaml-back
changes to requirements.yaml which allow local dev
> Multimesh david changes

- docs/Deploy with Minikube.md
This PR adds some minor clarifications per discussions in https://notes.deciphernow.com/t/notes-minikube-local-deployment/745/1 . Overall, the document was easy to follow and informative even for people with little background knowledge like myself.
N/A
N/A
4. Demonstrate the code is solid. Example: The exact commands you ran …
> Adding some clarifications

- docs/Deploy with Minikube.md
- edge/templates/edge-ingress.yaml
- greymatter/requirements-dev.yaml
- Add instructions for GM minikube install on an ec2
- Update greymatter/requirements-dev.yaml so it contains the latest core GM dependencies
- Add annotations to `edge-ingress.yaml` that mirror the ingress setup we have in our deployed OpenShift environment
- N/A
<br/><br/>
Yes
<br/><br/>
4. Demonstrate the code is solid. …
> Update minikube setup

- catalog/values.yaml
- docs/Deploy with Minikube.md
- docs/Service Accounts.md
- greymatter.yaml
@justincely and @joshua-rutherford, you both reported errors with YAML parsing. This should fix both cases.
Please re-deploy when you test this to confirm the fixes.
> fix YAML parsing errors

- catalog/templates/catalog.yaml
- greymatter-secrets.yaml
- greymatter/requirements.yaml
- slo/values.yaml
Resolves #294 
- fixes catalog yaml when spire is enabled
- fixes warnings on helm install
<br/><br/>
- addded a name for the data mongo secret 
- uncommented empty certs in slo/values.yaml
<br/><br/>
n/a
<br/><br/>
4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos …
> cleanup warnings on install

- docs/Getting Started.md
- gm-control-api/Chart.yaml
- gm-control-api/json/services/proxy.json
- greymatter/requirements.yaml
- greymatter/values.yaml
This PR adds the ability to enable or disable observables per service.  
This new section is needs to be added to `.Values.global`:
```
<br/><br/>
<br/><br/>
> Adds the ability to enable basic observations per service

- dashboard/Chart.yaml
- gm-control-api/Chart.yaml
- greymatter/Chart.yaml
- greymatter/requirements.yaml
- slo/Chart.yaml
Version bump after recent PR
<br/><br/>
None
<br/><br/>
No
<br/><br/>
Just a version bump after already approved PRs
<br/><br/>
> chart bug fixes for slo,gm-control-api,dashboard

- greymatter/requirements.yaml
- slo/Chart.yaml
- slo/templates/postgres-certs.yaml
- slo/templates/postgres-slo-overrides.yaml
- slo/templates/slo.yaml
- slo/values.yaml
A prior PR inadvertantly updated the postgres ssl cert names, and a customer's postgres container is very hardcoded to use postgres.crt
none
N/A
templated
> reverts to prior postgres cert names

- gm-control-api/Chart.yaml
- gm-control-api/json/services/proxy.json
- greymatter/requirements.yaml
Fixes an missing command from #304 
none
none
maybe i should do these more often...
closes #308
> add the missing comma between the proxy_filters

- gm-control-api/Chart.yaml
- gm-control-api/values.yaml
- greymatter/requirements.yaml
Resolves #284 by removing the first duplicate env var key entry
none
n/a
Just removed a duplicate entry
> remove duplicate persister type env var

- dashboard/templates/prometheus-configmap.yaml
- dashboard/values.yaml
- greymatter.yaml
See #286 for details.
This PR was created since the original working branch for #286 is now a protected branch and PR comments cannot be addressed in that branch. A new branch was created off of release-2.0 and merged the original commit as well as the changes initiated by the PR comment.
> Continuation of #286

- dashboard/Chart.yaml
- dashboard/templates/prometheus-configmap.yaml
- greymatter/requirements.yaml
There was an recent PR that had an error.  An `if` statement was never closed properly.  Instead of using an `{{- end }}`, an `{{- else }}` was accidently used.
resolves #316
n/a
n/a
> replace the bad else with and end

- control/Chart.yaml
- control/values.yaml
- gm-control-api/Chart.yaml
- gm-control-api/values.yaml
- greymatter.yaml
- greymatter/requirements.yaml
- greymatter/values.yaml
Resolves #325 
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
> bump control, control-api, cli to 1.0.2

- docs/Caveats and Notes.md
- docs/Deploy with Minikube.md
- docs/Getting Started.md
- docs/Ingress.md
This PR simply cleans up the docs.
n/a
n/a
n/a
n/a
> minor docs cleanup

- Makefile
- ci/scripts/build-credentials.sh
- ci/scripts/s3credentials.template
- ci/scripts/show-voyager.sh
- docs/Deploy with Minikube.md
This change will allow the quickstart credentials builder to config S3 properly. This is the follow on PR based on tilleryd's suggestions.
<br/><br/>
None
<br/><br/>
Yes
<br/><br/> …
> Allow script to setup S3 as well.

- Makefile
- docs/Deploy with Minikube.md
- greymatter.yaml
- additional update documentation relating to `greymatter-minikube.yaml` after deleting `greymatter-minikube.yaml` file in https://github.com/DecipherNow/helm-charts/pull/341
none
no documentation required
4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull …
> removed references to greymatter-minikube.yaml

- README.md
- docs/Generating k8s Config.md
- docs/Generating k8s Configs with Helm.md
<br/>
Resolves #353 
<br/>
<br/>n/a<br/>
<br/>n/a<br/>
<br/>n/a<br/>
> docs: using helm to generate k8s config

- Makefile
Minikube needs the correct global.environment setting this has changed around a bit in the past week. This PR fixes the make target.
<br/><br/>
None
<br/><br/>
NA
<br/><br/>
Same behavior as before.
<br/><br/>
> Update to make to set environment correctly.

- data/Chart.yaml
- data/templates/mongo-configmap.yaml
- data/templates/mongo-passwords.yaml
- data/values.yaml
- greymatter/requirements.yaml
This updates how the mongo credentials are created and used.  The credentials now require a `gmdata_username` and `gmdata_password` and use this information to create a new user in Mongo that GM Data will use to connect.
resolved #350 
`.values.mongo.credentials` now looks like this 
```yaml
credentials:
secret_name: 'mongo-credentials'
root_username: 'mongo'
root_password: 'mongo'
database: 'gmdata' …
```
> update the mongo credentials

- .gitignore
- Makefile
- ci/scripts/install-voyager.sh
- ci/scripts/voyager.patch
…patches and then installs.
Voyager's latest release has a small problem. This commit updates voyager to latest and applies a patch before installing. Updating to the latest voyager will let us move our k8s version to 1.16 which comes paired with minikube 1.4.0. That means that minikube 1.3.1 will be depreciated for helm-chart support soon.
<br/><br/>
NA
<br/><br/>
No. This is something to discuss though. …
> Voyager Minikube

- greymatter.yaml
Updates greymatter.yaml with the new mongo credentials from #370
Only if you want to make updates to the default values.
n/a
David G. has verified this in this setup
> Update greymatter.yaml  with new mongo values

- greymatter/Chart.yaml
matches up the greymatter/chart.yaml `appVersion` and `version`.
n/a
n/a
n/a
> update greymatter appversion to match release version

- .gitignore
- dashboard/Chart.yaml
- dashboard/templates/dashboard-certs.yaml
- dashboard/templates/dashboard.yaml
- dashboard/templates/prometheus-configmap.yaml
- dashboard/values.yaml
- greymatter-secrets.yaml
- greymatter.yaml
- greymatter/requirements.yaml
- greymatter/values.yaml
- slo/Chart.yaml
- slo/templates/slo-certs.yaml
- slo/templates/slo.yaml
- slo/values.yaml
This PR updates gm-dashboard and gm-slo to their latest versions. The primary change is to support TLS.
n/a
n/a
- change `requirements.yaml` to run local charts for dashboard and slo
- …
> update dashboard and slo to latest releases

- catalog/Chart.yaml
- ci/Jenkinsfile
- control/Chart.yaml
- dashboard/Chart.yaml
- data/Chart.yaml
- data/templates/mongo-service.yaml
- data/templates/mongo.yaml
- data/values.yaml
- docs/Getting Started.md
- edge/Chart.yaml
- gm-control-api/Chart.yaml
- greymatter.yaml
- greymatter/Chart.yaml
- greymatter/requirements.yaml
- jwt-gov/Chart.yaml
- jwt-gov/templates/redis-service.yaml
- jwt/Chart.yaml
- jwt/templates/redis-service.yaml
- slo/Chart.yaml
- slo/templates/postgres-service.yaml
- spire/Chart.yaml
* Remove the `ClusterIP: None` from any service.  This prevents k8s from performing proper load balancing to an service
* Allows a user to define the `StorageClassName` for the mongo PersistentVolumeTemplate.
resolves #167 
resolves #378 
Mongo PVC info was moved into a new grouping:
```yaml
mongo:
storage:
size: 40
#storageClassName: "-"
```
3. Have you documented any additional setup steps or …
> 378 storageclass

- Makefile
- ci/scripts/show-voyager.sh
- docs/Deploy with Minikube.md
- edge/templates/edge-ingress.yaml
<br/><br/>
Pin the voyager port to 30000 to make training and dev setup easier
Resolves #385 
<br/><br/>
/na
<br/><br/>
<br/><br/>
Run `make minikube` to test
> Pin voyager port

- control/Chart.yaml
- gm-control-api/Chart.yaml
- greymatter/requirements-dev.yaml
- greymatter/requirements.yaml
Fix control and control-api versions 2.2.1 -> 2.1.2
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
> fix chart versions

- .circleci/config.yml
@moosecanswim this should fix the issue with the circle ci build failing for release branches.
> minor updates to nexus_url for hosting

- greymatter.yaml
Relates to https://github.com/DecipherNow/helm-charts/issues/404. All mentions of aac removed from greymatter.yaml
<br/><br/>
None though greymatter.yaml was changed but not in a backward incompatible way.
<br/><br/>
NA
<br/><br/> …
> Removed aac from greymatter.yaml.

- catalog/Chart.yaml
- catalog/templates/catalog.yaml
- greymatter/requirements.yaml
This PR adds a readiness probe for catalog. Set version to 2.1.3 assuming the docker secret PR gets pulled first.
<br/><br/>
None
<br/><br/>
NA
<br/><br/>
Tested in Minikube.
<br/><br/>
> Readiness probe for catalog

- data/Chart.yaml
- data/templates/data.yaml
- greymatter/requirements.yaml
Adding a readiness probe for gm-data. Uses /list/1/ endpoint
<br/><br/>
None
<br/><br/>
NA
<br/><br/>
Tested in minikube.
<br/><br/>
> Readiness probe for data

- dashboard/Chart.yaml
- dashboard/templates/prometheus.yaml
- greymatter-service-accounts.yaml
- greymatter/requirements.yaml
Fixes issue https://github.com/DecipherNow/helm-charts/issues/362 . Prometheus will use it's own service account and its service account is now a cluster role.
<br/><br/>
None
<br/><br/>
NA
<br/><br/>
4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull …
> Correcting prometheus service account setup.

- catalog/values.yaml
- greymatter.yaml
While attempting to understand what needs to change along with certificates I learned that several values with DNs were obsolete and unused. This PR removes those values. I don't think this PR requires an update to chart versions.
n/a
n/a …
> remove obsolete configs

- data/templates/data.yaml
Remove bad conditional logic in data.yaml securityContext.
No
n/a
1. Ran `make minikube` and confirm the security context by running `kubectl get -l app=internal-data -o yaml`
> fix data securityContext

- greymatter.yaml
<br/><br/>
Update greymatter.yaml to automaticall create the SA for prometheus
<br/><br/>
Set the prometheus SA to `create: true`
<br/><br/>
<br/><br/>
Test that you can access service …
> create prometheus sa by default

- edge/Chart.yaml
- edge/values.yaml
- greymatter/requirements-dev.yaml
- greymatter/requirements.yaml
improper formatting in the `edge/values.yaml` led to creating an ingress like this:
```yaml
---
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
name: edge
namespace: default
annotations:
ingress.appscode.com/ssl-passthrough: "true"
ingress.appscode.com/type: NodePort
kubernetes.io/ingress.class: voyager
spec:
rules:
- backend:
serviceName: edge
servicePort: 8080
nodePort: "30001"
port: "80"
tcp: null
- backend:
serviceName: edge …
```
> Patch ingress 428 pr

- dashboard/Chart.yaml
- dashboard/templates/dashboard.yaml
- greymatter/requirements-dev.yaml
- greymatter/requirements.yaml
This creates a readiness probe for dashboard.
<br/><br/>
None.
<br/><br/>
NA
<br/><br/>
Ran in minikube.
<br/><br/>
> Readiness Probe for dashboard.

- catalog/Chart.yaml
- catalog/templates/catalog.yaml
- greymatter/Chart.yaml
- greymatter/requirements.yaml
This PR fixes the bug when consul is enabled, closes #450 
<br/><br/>
This is an already existing option, so no changes are required.
Set .Values.consul.enabled to true and set the consul server address (full instructions are in the docs https://github.com/DecipherNow/helm-charts/blob/release-2.1/docs/Consul.md#minikube-setup)
<br/><br/>
3. Have you documented any additional setup steps or …
> fix catalog readiness probe

- ci/scripts/build-credentials.sh
Currently when run make credentials your password is visible on the command line. This change hides your input.
<br/><br/>
None
<br/><br/>
NA
<br/><br/>
Run "make credentials" and see …
> Don't show characters as user is typing in make credentials.

- docs/Ingress.md
This PR only updates the ingress.md, providing more information for how to set up and configure for Nginx Ingress
None
N/a
n/a
> Update ingress documentation

- greymatter/Chart.yaml
- greymatter/values.yaml
This PR updates the capabilities field in catalog of many of the greymatter services. It also bumps up the chart version.
<br/><br/>
NA
<br/><br/>
NA
<br/><br/>
Ran in minikube. …
> Service capabilities catalog

- data/templates/data.yaml
Adding data readiness probe back to data
<br/><br/>
None
<br/><br/>
NA
<br/><br/>
Good old minikube.
<br/><br/>
> Data readiness probe added back

- control/values.yaml
- edge/values.yaml
- gm-control-api/values.yaml
- greymatter.yaml
- greymatter/values.yaml
Changes
- Update control/control-api/cli/proxy to latest in docker-dev repo
To test
- `make dev`
> update control plane

- .circleci/config.yml
Update the docker image used by the ci and pin it to a version that has helm3 support, pint the sed at the chart.yaml file since the requiremenst.yaml content was rolled into that for helm3
none
none
4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull …
> Ci helm3 support

- .circleci/config.yml
pin the ci to a specific version of helm-packager (tagged with the helm version used)
<br/><br/>
<br/><br/>
<br/><br/>
> pin ci to set version of helm packager

- docs/Deploy with Minikube.md
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
> update docs deploy to minikube docs to use helm 2.16.1

- docs/Deploy with Minikube.md
- docs/Getting Started.md
Points certs links in the docs to the certs hosted in this repo.
> point quick start certs to certs in chart

- fabric/control-api/json/special/proxy.json
- sense/dashboard/values.yaml
- sense/values.yaml
Need this quick fix in for monday morning for a POC kickoff.  Deployed to EKS to verify.
> fix remaining docker-dev urls, reduce dashboard/prometheus requirements

- sense/Chart.yaml
- sense/dashboard/Chart.yaml
- sense/dashboard/templates/prometheus-configmap.yaml
Closes #543
None
None needed, just update charts and re-install
After installation, go to `/services/prometheus/latest/targets` and confirm additional `envoy-metrics` targets are added.
> Always scrape Envoy stats metrics

- data/Chart.yaml
- data/gm-data/Chart.yaml
- data/jwt-gov/Chart.yaml
- data/jwt/Chart.yaml
- edge/Chart.yaml
- fabric/Chart.yaml
- fabric/control-api/Chart.yaml
- fabric/control/Chart.yaml
- secrets/Chart.yaml
- sense/Chart.yaml
- sense/catalog/Chart.yaml
- sense/dashboard/Chart.yaml
- sense/slo/Chart.yaml
- spire/Chart.yaml
- spire/agent/Chart.yaml
- spire/server/Chart.yaml
Updates the release-2.2 charts to change all versions to a 2.2.0
None
none needed
run `make clean` && `make install`
> Update 2.2 versions

- sense/Chart.yaml
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
> Fix unaddressed merge conflict

- fabric/Makefile
Adds the globals file as an input for fabric charts.
None
none needed
make install
> Update Makefile to point to globals

- ci/scripts/k3d.sh
- docs/Deploy with K3d.md
- add instructions for installing locally with k3d
> Update k3d docs

- docs/Deploy with K3d.md
- spire/Makefile
Just some Makefile and readme updates
> Makefile and readme updates

- Makefile
- docs/Deploy with K3d.md
Running `make k3d` didn't have an additional instruction to export `KUBECONFIG`. If I was running `./ci/scripts/k3d.sh` directly I could run it like `. ./ci/scripts/k3d.sh` to source the exported env var to the parent shell. In lieu of running through Make, I opted to make it as clear as possible that that's a final step. This also means a developer doesn't have to rely on the documentation.
None
3. …
> K3d updates

- README.md
- docs/Deploy with Minikube.md
- docs/Getting Started.md
Old support link, `support.deciphernow.com`, needed to be changed to the newer `support.greymatter.io`.
> updated support link

- LICENSE
adds a license to release-2.2 branch
> add license to release-2.2

- .circleci/config.yml
publish 2.2 charts to nexus prod
none
none
make sure the cirleci job runs
> Publish 2.2

- .circleci/config.yml
publish a fabric-gov helm chart which includes jwt-gov chart
none
none
if ci works check nexus for the package
> publish fabric-gov

- .circleci/config.yml
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
> Package fabric gov

- fabric/jwt-gov/templates/jwt.yaml
match jwt-gov to jwt for the http_port and http_ports envar... needs the `'`
> Quote jwt gov port

- ci/scripts/s3credentials.template
matches s3credentials.template with credentials.template
closes #629
n/a
n/a
run `make credentials` and enter `y` to the s3 question
run `make secrets` and ensure the secrets charts …
> brings the s3credentials.template in line with credentials.template

- .circleci/config.yml
- fabric/jwt-gov/templates/jwt.yaml
This change is required to:
1) bring jwt and jwt-gov charts inline (gov had a extra unused volume and did not have consul configs... maybe we should consider making them one chart with more logic)
2) source $BASH_ENV so NEXUS_URL is actually used
3) use sed to change fabric chart to fabric-gov
none
none
4. Demonstrate the …
> Jwtgov unusedvolume

- .circleci/config.yml
Modify ci script to package jwt (regular for internal) and jwt-gov in fabric-gov chart
none
none
ci passed for helm-staging and deployment worked as expected.
> update fabric chart to have just one jwt-gov

- .circleci/config.yml
match the helm-stage to helm-hosted pushing stages
> Match stages

- edge/templates/_helpers.tpl
- edge/templates/edge-ingress.yaml
compensates for known issue in openshift 3.11 that marks status as a required field
https://github.com/openshift/origin/issues/24060
none
none
ci used to push this to helm-staging. …
> Openshift route fix

- data/Makefile
- edge/Makefile
- fabric/Makefile
- sense/Makefile
When installing in openshift these lines override the environment set in global.yaml
<br/><br/>
None
<br/><br/>
<br/><br/>
Running in openshift these changes allow control, data, and …
> [release-2.2] Global Environment

- secrets/values.yaml
sed default rds.enabled to false
> Postgres credentials

- data/gm-data/values.yaml
- data/values.yaml
- fabric/control-api/values.yaml
- fabric/control/values.yaml
- fabric/jwt-gov/values.yaml
- fabric/jwt/values.yaml
- fabric/values.yaml
- global.yaml
- sense/catalog/values.yaml
- sense/dashboard/values.yaml
- sense/slo/values.yaml
- sense/values.yaml
Upgrade image versions to match https://docs.greymatter.io/v/1.2-dev/introduction/release_notes
> Version upgrades

- fabric/jwt/values.yaml
- sense/catalog/values.yaml
- sense/values.yaml
Fixed all users.json entries to use the greymatter.io address. Catalog was not able to connect to data because it's certs used engineering@greymatter.io.
To test
- `make install`
- Check that you can get to the dashboard
> fix jwt users

- docs/Deploy with K3d.md
There was no note about how much disk to allocate to Docker.
none
none
I was able to install the mesh once disk resources were increased.
> update k3d doc to include Docker disk resource

- fabric/jwt-gov/values.yaml
- incorporate changes from https://github.com/DecipherNow/gm-jwt-security-gov/pull/138 and https://github.com/DecipherNow/gm-jwt-security-gov/pull/137
none
n/a
> updated gm-jwt-security-gov to version 1.1.2

- secrets/templates/data-secret.yaml
- secrets/templates/internal-data-secret.yaml
- secrets/templates/internal-mongo-passwords.yaml
- secrets/templates/internal-redis-password.yaml
- secrets/templates/mongo-passwords.yaml
- secrets/templates/postgres-credentials.yaml
- secrets/templates/redis-password.yaml
- secrets/values.yaml
Adding helm configuration logic to create random strings for passwords when a user does not provide passwords.
<br/><br/>
<br/><br/>
- Leave updated passwords fields empty and run `make …
> adding logic to create random strings for pws

- edge/templates/edge-service.yaml
- voyager/Makefile
Updated edge service type from Load Balancer to empty string because we already have an ingress-controller that does the load balancing.
closes #669 
<br/><br/>
<br/><br/>
Run `make …
> updating edge service type

- .circleci/config.yml
Our Nexus server changed and this update points the CI to the new one.
n/a
n/a
CircleCI packages and publishes for the non-master branches.
> Update CI for the new Nexus Server

- .circleci/config.yml
This is just an update to the previous commit message. The prior message had `[ci skip]` so Circle didn't run. This PR updates the commit message to trigger circle
> Updates the CI to use new Nexus server

- .circleci/config.yml
This is just a minor update to trigger a circle ci build
> minor update to trigger a new build

- secrets/templates/edge-egress-secret.yaml
updating template to check for egress cert instead of ingress in egress-template file
<br/><br/>
<br/><br/>
<br/><br/>
> update check for egree cert

- edge/templates/edge-service.yaml
- voyager/Makefile
Updated edge service type to nothing
<br/><br/>
<br/><br/>
<br/><br/>
> updated edge service type

- Makefile
If installing via `make k3d`, then automatically configure ingress to be of type LoadBalancer.
no
n/a
Installed via k3d and was able to access the dashboard at https://localhost:30000.
> use ingress type of LoadBalancer for k3d

- ci/scripts/build-credentials.sh
- docs/Deploy with Minikube.md
- docs/Generic Install.md
- docs/Getting Started.md
We have a new Nexus server, but docs mention the old one
N/A
N/A
N/A
> Update helm chart references to new Nexus repo

- secrets/templates/data-secret.yaml
- secrets/templates/internal-data-secret.yaml
Fixes an error from changes made to #709. If the `master_key` was given, the secret would not populate b/c of an error in the logic
n/a
n/a
Update the `secrets/values.yaml` and provide …
> fixes a master_key error; missed a test case that would\'ve caught this

- fabric/control-api/json/services/listener.json
- fabric/control-api/json/special/route-jwt-slash.json
- fabric/control-api/json/special/route-jwt.json
<br/><br/>
closes #648 
closes #699 
Adds impersonation filter back for no spire install and switches the default jwt service used for the jwt filter to be the external one
> Impersonation

- ci/scripts/credentials.template
- ci/scripts/s3credentials.template
- data/gm-data/values.yaml
- data/values.yaml
- edge/values.yaml
- fabric/control-api/values.yaml
- fabric/control/values.yaml
- fabric/jwt-gov/values.yaml
- fabric/jwt/values.yaml
- fabric/values.yaml
- greymatter-secrets.yaml
- observables/custom-values-files/kibana-proxy-values.yaml
- proxy/values.yaml
- secrets/values.yaml
- sense/catalog/values.yaml
- sense/dashboard/values.yaml
- sense/slo/values.yaml
- sense/values.yaml
This PR replaces the old `docker.production.deciphernow.com` registry with the new `docker.greymatter.io` registry.
n/a
n/a
I tested via the following:
1. `make credentials`
1. `make …
> update to docker.greymatter.io registry

- data/gm-data/templates/mongo.yaml
- fabric/control-api/templates/control-api.yaml
- global.yaml
- sense/dashboard/templates/prometheus.yaml
- sense/slo/templates/postgres.yaml
- sense/slo/templates/slo.yaml
Made changes to `securityContext ` spec attribute in the charts. Upon testing , the `securityContext ` is same for OCP versions and kubernetes environments.  
N/A
Yes, added comments …
> Ocp4 gm deployment

- edge/values.yaml
Updated edge version
<br/><br/>
<br/><br/>
<br/><br/>
> updated edge version

- .circleci/config.yml
Fixes Fabric packaging in circleci (did not include redis chart in last PR)
> Package redis chart

- fabric/control-api/config/bootstrap.sh
- fabric/control-api/json/special/cluster-edge-prometheus.json
- fabric/control-api/json/special/cluster-prometheus.json
- fabric/control-api/json/special/domain-egress-prometheus.json
- fabric/control-api/json/special/domain-prometheus.json
- fabric/control-api/json/special/listener-egress-prometheus.json
- fabric/control-api/json/special/listener-prometheus.json
- fabric/control-api/json/special/proxy-prometheus.json
- fabric/control-api/json/special/route-1-edge-prometheus.json
- fabric/control-api/json/special/route-2-edge-prometheus.json
- fabric/control-api/json/special/route-prometheus.json
- fabric/control-api/json/special/shared_rules-edge-prometheus.json
- fabric/control-api/json/special/shared_rules-prometheus.json
- fabric/control-api/values.yaml
MR migrated configuration object creation for prometheus under special
Closes #743 
N/A
Configuration is the same, just the steps have been updated 
Create cluster and all the service …
> initial commit to refactor prometheus confs

- data/gm-data/values.yaml
- data/values.yaml
- edge/values.yaml
- fabric/control-api/values.yaml
- fabric/jwt-gov/values.yaml
- fabric/jwt/values.yaml
- fabric/values.yaml
- global.yaml
- proxy/values.yaml
- sense/catalog/values.yaml
- sense/dashboard/values.yaml
- sense/slo/values.yaml
- sense/values.yaml
fixes proxy version to match control plane
> from 1.4.4 to 1.5.0-dev

- data/gm-data/templates/mongo.yaml
- edge/values.yaml
- fabric/control-api/templates/control-api.yaml
- global.yaml
- sense/dashboard/templates/prometheus.yaml
- sense/slo/templates/postgres.yaml
- sense/slo/templates/slo.yaml
Pushing changes to secruity_context from release2.2
N/A
N/A
create cluster and cluster should be running successfully.
> Updates from release2.2

- .chart-testing/services.yaml
- .circleci/config.yml
- .github/workflows/linter.yaml
To make the switch to the greymatter-io organization easier, this PR goes ahead and switches to using a context for the Nexus User and Password
> Use CircleCI context for Nexus User & Password information

- .github/workflows/helm-test.yaml
- .github/workflows/helm.yaml
- .github/workflows/linter.yaml
This adds a GitHub action to lint and test the charts on a pull request.
> Gh actions test

- data/Chart.yaml
- data/gm-data/Chart.yaml
- data/gm-data/templates/_helpers.tpl
- docs/Ingress.md
- edge/Chart.yaml
- edge/templates/edge-service.yaml
- edge/values.yaml
- fabric/Chart.yaml
- fabric/control-api/Chart.yaml
- fabric/control-api/templates/control-api-service.yaml
- sense/Chart.yaml
- sense/catalog/Chart.yaml
- sense/catalog/templates/catalog-service.yaml
> 2.3 gke / configurable ingress

- README.md
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
> Fix formatting of the README

- fabric/values.yaml
enabling the resources attributes for gm services
N/A
N/A
deploy the cluster and all the services should be able to deploy successfuly.
When testing in Openshift control should not die …
> adding resources to the gm services

- fabric/Chart.yaml
- fabric/control/Chart.yaml
- fabric/control/templates/control.yaml
We are unable to set the control resources currently b/c the templating is incorrect. 
None
None
```console
control:
control:
...
resources:
limits:
cpu: 500m
memory: 1Gi
requests:
cpu: …
```
> Fixes the templating for Control resources

- fabric/Chart.yaml
Increments the fabric charts so that CI will work as expected.
> Fixes the templating for Control resources (#777)

- .circleci/config.yml
- docs/Getting Started.md
Fixed spelling issue from issue #724 .
> Fixed spelling issue (#724)

- .github/workflows/release.yaml
This PR should allow us to package the Fabric Gov chart.
> Release the Fabric Gov charts

- README.md
Updated the README with instructions on how to perform integration testing.
> Update README with integration testing instructions

- .github/workflows/release.yaml
- .github/workflows/sync-readme.yaml
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
> Fix GitHub Actions

- spire/Chart.yaml
- spire/Makefile
- spire/agent/Chart.yaml
- spire/agent/templates/daemonset.yaml
- spire/agent/values.yaml
updating spire helm-chart and makefile to add extra steps to allow hostaccess/privilege to spire service-account user
N/A
<br/><br/>
Deploy OCP4.6 cluster
Update global.environment …
> adding updates to deploy spire on ocp46 successfully

- observables/Makefile
I forgot to add this flag in my last pr when eks = false - fixes elasticsearch install
> add flag when eks false

- secrets/Chart.yaml
Updated the Secrets Chart.yaml to release 2.3.0. #831
> Updated secrets.yaml for release-2.3 (#831)

- observables/Makefile
- observables/custom-values-files/logstash-values.yaml
This adds the last couple of flags to make observables install correctly
> fix flags for elk stack

- data/Chart.yaml
- data/gm-data/Chart.yaml
- data/gm-data/values.yaml
- data/values.yaml
- fabric/Chart.yaml
- fabric/control-api/Chart.yaml
- fabric/control-api/values.yaml
- fabric/values.yaml
- sense/Chart.yaml
- sense/catalog/Chart.yaml
- sense/catalog/values.yaml
- sense/values.yaml
Updates gm-data to 1.1.5.
none
n/a
n/a
> update gm-data to 1.1.5

- fabric/Chart.yaml
- fabric/control-api/Chart.yaml
- fabric/control-api/values.yaml
- fabric/values.yaml
- sense/Chart.yaml
- sense/catalog/Chart.yaml
- sense/catalog/values.yaml
- sense/dashboard/Chart.yaml
- sense/dashboard/values.yaml
- sense/values.yaml
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
> bump dashboard version, bump related chart versions

- fabric/Chart.yaml
Bumping Fabric chart to 3.0.5 due to failed linting as indicated in https://github.com/greymatter-io/helm-charts/issues/854.
none
n/a
n/a
> update fabric chart to 3.0.5

- fabric/Chart.yaml
- fabric/control-api/Chart.yaml
- fabric/control-api/templates/control-api-init-hook.yaml
- fabric/control-api/values.yaml
- fabric/redis/Chart.yaml
- fabric/redis/templates/redis.yaml
- fabric/redis/values.yaml
- fabric/values.yaml
- global.yaml
resolves #841 
resolves #814 
- remove centos redis image. Currently working in openshift
- add redis health check to control-api-init container
<br/><br/>
<br/><br/>
<br/><br/> …
> control-api / redis race condition

- sense/Chart.yaml
- sense/dashboard/Chart.yaml
- sense/dashboard/values.yaml
- sense/values.yaml
This will lower the resources for dashboard
none
none needed
I tested this in a devinabox instance using k3d
> adjust dashboard resources

- README.md
updates the readme with development versioning informaiton
> Update README.md with development information

- Makefile
- docs/Deploy with K3d.md
Closes #904 
none
I updated the docs where `make destroy` was referenced
I deployed locally and destroyed my k3d cluster with `make destroy-k3d`.
> split-destroy-command

- sense/Chart.yaml
- sense/dashboard/Chart.yaml
- sense/dashboard/templates/prometheus.yaml
- sense/slo/Chart.yaml
- sense/slo/templates/postgres.yaml
- sense/slo/templates/slo.yaml
Similar to #911, addtional Prometheus, Postgres and SLO need to have the securityContext checked for an OpenShift or not.
n/a
n/a
Template with `globals.environment` set to `eks` and …
> update securityContext for other services

- Makefile
- secrets/Makefile
Fixes a recently introduced error with `make credentials`
> fix makefile calls to make credentials

- .github/workflows/release.yaml
> Update chart releaser version

- fabric/Chart.yaml
- fabric/control-api/Chart.yaml
- fabric/control-api/templates/control-api-init-hook.yaml
- fabric/jwt-gov/Chart.yaml
- fabric/jwt-gov/templates/jwt.yaml
- fabric/jwt/Chart.yaml
- fabric/jwt/templates/jwt.yaml
- sense/Chart.yaml
- sense/catalog/Chart.yaml
- sense/catalog/templates/catalog-init-hook.yaml
- sense/catalog/templates/catalog.yaml
- sense/dashboard/Chart.yaml
- sense/dashboard/templates/prometheus.yaml
- sense/slo/Chart.yaml
- sense/slo/templates/postgres.yaml
- spire/Chart.yaml
- spire/agent/Chart.yaml
- spire/agent/templates/daemonset.yaml
- spire/server/Chart.yaml
- spire/server/templates/statefulset.yaml
This PR will automatically bounce pods when their coresponding configmaps are updated
none
no additional steps
To test this install the mesh like normal.  Then add a namespace to …
> Link cm rs

- .github/workflows/release.yaml
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
> remove auto pr creation

- docs/Deploy with K3d.md
This changes the documentation to include two missing steps in the installation process (logging into docker and generating certificates). It also reorganizes the documentation to make it (hopefully) easier to read and understand.
<br/><br/>
None
<br/><br/>
N/A
<br/><br/>
4. Demonstrate the code is solid. Example: The exact …
> Update docs/Deploy with K3d.md

- global.yaml
- spire/Chart.yaml
- spire/agent/Chart.yaml
- spire/agent/templates/daemonset.yaml
- spire/agent/values.yaml
- spire/server/Chart.yaml
- spire/server/templates/statefulset.yaml
- spire/server/values.yaml
- spire/values.yaml
Requested in Clubhouse Story 3609. A client requested the ability to pull Spire images from a private repository.
<br/><br/>
<br/><br/>
<br/><br/>
Built a local GM cluster using the new …
> Replaced hard-coded Spire images with variable-ized values.

- .chart-testing/edge-secrets.yaml
- .chart-testing/fabric-sense-data.yaml
- .chart-testing/services.yaml
- .github/workflows/release.yaml
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
> Backported ci process changes

- spire/Chart.yaml
- spire/agent/Chart.yaml
- spire/agent/templates/config-configmap.yaml
- spire/agent/values.yaml
- spire/server/Chart.yaml
- spire/server/templates/config-configmap.yaml
- spire/server/values.yaml
- spire/values.yaml
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
> Backport 2.4 Spire upgrade to main

- Makefile
- docs/Deploy with K3d.md
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>
> Backported splitting the destroy command in the Makefile from 2.4

- .gitignore
- data/Chart.yaml
- data/gm-data/Chart.yaml
- edge/Chart.yaml
- fabric/Chart.yaml
- fabric/control-api/Chart.yaml
- fabric/control/Chart.yaml
- fabric/jwt-gov/Chart.yaml
- fabric/jwt/Chart.yaml
- fabric/redis/Chart.yaml
- proxy/Chart.yaml
- secrets/Chart.yaml
- sense/Chart.yaml
- sense/catalog/Chart.yaml
- sense/dashboard/Chart.yaml
- sense/slo/Chart.yaml
- spire/Chart.yaml
- spire/agent/Chart.yaml
- spire/server/Chart.yaml
Bumped the Chart versions for all components in order to cut the final Helm Chart releases for GM 1.3. This is in preparation for integrating the GM 1.6 changes.
<br/><br/>
<br/><br/>
<br/><br/>
4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request …
> Bumped chart versions on new main branch to generate new helm releases
