greymatter-io/helm-charts

greymatter/requirements.yaml
Sets the Grey Matter requirements to pull from nexus instead of locally
none
none
```console
➜  helm-charts git:(greymatter-req-update) helm dep update greymatter
Saving 11 charts …
```
=> pull charts from nexus not locally

docs/Getting Started.md
*Resolves #257
- `s^./greymatter-custom.yaml^../greymatter-custom.yaml^`
- `s^./greymatter-custom-secrets.yaml^../greymatter-custom-secrets.yaml^`
- View the modified file in the pull request and insure the links work.
=> fix links to custom yaml in getting started

greymatter.yaml
Closes #278 
The full description of why the fix was needed is in the above issue. 
<br/><br/>
I changed the default here to match the defaults in JWT server.  
<br/><br/>
No
<br/><br/> …
=> set default userfield to email in gm-data

dashboard/templates/prometheus.yaml, docs/Getting Started.md, docs/Ingress.md, gm-control-api/json/special/domain.json, gm-control-api/templates/gm-control-api.yaml, helm-service-account.yaml, slo/templates/postgres.yaml, slo/templates/slo.yaml, slo/values.yaml
This PR incorporates changes for deploying on bare Kubernetes (no openshift, minishift, minikube).  The main additions are:
- `securityContexts` to allow services with volume mounts to run properly.  
- modifying the edge `domain` to accept request with any HOST header keyword.  this allows port-forwarding (and may fix some CLI bugs people are hitting)
- makes the postgres image the same for k8s and openshift installations.  
- add a service …
=> update for running on raw k8s

.gitignore, Makefile, ci/scripts/build-credentials.sh, ci/scripts/credentials.template, ci/scripts/install-voyager.sh, docs/Deploy with Minikube.md
1. No related issue.
<br/><br/>
2. What **changes to custom.yaml** are required? None
<br/><br/>
3. Have you documented any additional setup steps or configurations options? Yes in Deploy Minikube.
<br/><br/>
4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI. 
```
nicholas@daily:~/Documents/helm-charts$ make minikube
minikube start -p gm-deploy --memory 6144 --cpus 6
* [gm-deploy] minikube v1.3.1 on Ubuntu 18.04
* Creating kvm2 VM (CPUs=6, Memory=6144MB, Disk=20000MB) ...
* Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
* Pulling images ...
* Launching Kubernetes ...
* Waiting for: apiserver proxy etcd scheduler controller dns
* Done! kubectl is now configured to use "gm-deploy"
helm init --wait …
```
=> Automation for minikube using make.

greymatter/templates/NOTES.txt
```
Once the environment has spun up you will be able to view Grey Matter's Dashboard at:
https://greymatter.default.staging.deciphernow.com/services/dashboard/latest/
```
is no longer accurate or valid for most deployments see [initial comment](https://github.com/DecipherNow/helm-charts/pull/341#pullrequestreview-305405421)
none
3. Have you documented any additional setup steps or configurations …
=> removed endpoint url note in greymatter/templates/NOTES.txt

catalog/Chart.yaml, catalog/templates/catalog.yaml, dashboard/templates/prometheus.yaml, docs/Deploy with Minikube.md, edge/templates/edge.yaml, greymatter/requirements.yaml, jwt-gov/templates/jwt.yaml, jwt-gov/templates/redis.yaml, jwt/Chart.yaml, jwt/templates/jwt.yaml, jwt/templates/redis.yaml
Kubernetes 1.16.0 deprecated several APIs that some Grey Matter charts are using.  These resources have been available at `apps/v1` for a long time, so this was just a matter of time before it broke.
resolves #276 
n/a
none
4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / …
=> Update from extensions/v1beta1 to apps/v1 + minor readme update

greymatter-secrets.yaml
We leverage the  `greymatter-secrets.yaml` custom file to store Grey Matter certificates and other secrets, but it did not include credentials for Mongo, Postgres and Redis.  This PR just moves them into this file so they're more visible for customers.
n/a
n/a
4. Demonstrate the code is solid. Example: The exact commands you …
=> bring credentials to greymatter-secrets so users know they exist

catalog/Chart.yaml, catalog/templates/_helpers.tpl, catalog/templates/bootstrap-zone-configmap.yaml, control/Chart.yaml, dashboard/Chart.yaml, dashboard/templates/_helpers.tpl, dashboard/values.yaml, data/Chart.yaml, data/templates/_helpers.tpl, documentation/Chart.yaml, documentation/templates/_helpers.tpl, edge/Chart.yaml, edge/templates/_helpers.tpl, gm-control-api/Chart.yaml, greymatter.yaml, greymatter/Chart.yaml, greymatter/requirements-dev.yaml, greymatter/requirements.yaml, jwt-gov/Chart.yaml, jwt-gov/templates/_helpers.tpl, jwt-gov/templates/jwt.yaml, jwt-gov/values.yaml, jwt/Chart.yaml, jwt/templates/_helpers.tpl, jwt/templates/jwt.yaml, jwt/values.yaml, slo/Chart.yaml, slo/templates/_helpers.tpl, slo/templates/slo.yaml, spire/Chart.yaml
This PR removes `.cluster.local` from each host definition that calls a service (`x.namespace.svc.cluster.local`) .  This change allows the service mesh to be deployed into a cluster with a custom dns (service ex: `x.namespace.svc.testdecipher` would be the service inside a cluster called testdecipher).
To test:
- launch ec2 or local minikube
- install helm
- install gm2
- ensure the dashboard is visable
- (optional) deploy service in another …
=> remove cluster.local

.github/workflows/release-pr-merged.yml, .github/workflows/release-pr-opened.yml
This PR changes the CI from Jenkins to GitHub Actions. Since the repo is public, we can leverage the GitHub Actions.  There are two workflows in this PR
1. Runs a helm package when a PR is submitted.  Reports to the PR as a Status check
2. Runs a helm package and deploys to Nexus when the PR is merged
I did as much testing as I could in my own environment.
I do not think this is the end of the necessary updates  to use GitHub Actions, but this should get us rolling again now that dev has died.
The necessary secrets have been created, but not yet verified in this repo.
This uses the GitHub Action at https://github.com/DecipherNow/greymatter-helm-action
=> Add the helm package greymatter actions

edge/Chart.yaml, edge/templates/_domain.tpl, edge/templates/_edge_volume_mounts.tpl, edge/templates/_edge_volumes.tpl, edge/templates/edge-secret.yaml, edge/templates/edge.yaml, edge/values.yaml, gm-control-api/Chart.yaml, gm-control-api/json/services/proxy.json, greymatter-secrets.yaml, greymatter.yaml, greymatter/Chart.yaml, greymatter/requirements.yaml
Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.
There are a lot of changes to this PR.  Specifically, it enables the `gm.impersonation` filter by default.  Full details of the bug can be found in the ticket below
Resolves #396 
This PR makes some significant changes to `greymatter.yaml` and to `greymatter-secrets.yaml`.  Anyone looking to use this version of Grey Matter will need to ensure they update any local references to these files, otherwise the mesh will not deploy correctly.
FYI - @danielpcox @tilleryd @kaitmore …
=> Enable Impersonation in the mesh

data/Chart.yaml, data/templates/data.yaml, data/values.yaml, greymatter.yaml, greymatter/requirements.yaml
Added gm-data `securityContext` to support non-Openshift deployments. EKS for example, has stricter security policies that require the pod to use the same user/group as the container.
In greymatter.yaml, data securityContext is enabled by default, but I didn't add the user/group values, which can be found in data/templates/data.yaml.
3. Have you documented any additional setup steps or configurations …
=> add gm-data securityContext supported by EKS

greymatter.yaml
Just needed to reduce the default logging level for gm-control.
See the one line change...
n/a
Here's a bunch of log messages from control. Notice no DEBUG.
```
9:47PM INF Creating …
```
=> info level logging for gm-control

data/templates/data.yaml, greymatter.yaml
Set gm-data security-context by
```
data:
...
securityContext:
enabled: false
```
n/a
Test steps:
1. deploy to Minikube and ensure that the security context is created by running …
=> disable gm-data security context by default

greymatter/Chart.yaml
Only increments the Grey Matter chart version to 2.1.5.  This was missed in my prior PR.
=> update gm chart to 2.1.5

docs/Service Accounts.md
This PR updates the Service Account documentation to add details on how to enable Grey Matter the ability to monitor services in other, non default, namespaces.
closes #456
=> Update service account documentation

data/Chart.yaml, data/values.yaml, greymatter/Chart.yaml, greymatter/requirements.yaml
`data/values.yaml` was updated to include sidecar configs that override global sidecar configs. The xds_host env var was hard coded to `control.default.svc.cluster.local` which meant gm-data wouldn't connect to gm-control in a namespace other than `default`. I removed the configs because this aligns with how we're managing sidecar configs in all the other charts.
none
3. Have you documented any …
=> remove data sidecar configs

ci/scripts/install-voyager.sh
Voyager 11.0.1 only works with later k8s versions with the validate=false flag enabled. Using minikube 1.4 you will not need this but the latest minikube will deploy a k8s that needs this.
<br/><br/>
None
<br/><br/>
NA
<br/><br/> …
=> Allows voyager version 11.0.1 to work with later k8s versions.

greymatter-secrets.yaml
When data has mongo ssl enabled it will use the mongo certs in greymatter-secrets.yaml. Unfortunately the removed lines in this PR cause helm to error out. Removing them restores desired functionality. mongo.ssl.name is what is used to choose the cert name anyways not mongo.ssl.certificates.name which is what is being removed.
<br/><br/>
Two lines of greymatter-secret.yaml is removed that would need …
=> mongo.ssl.enabled fix

dashboard/templates/dashboard.yaml, data/templates/data.yaml
This implements the liveness probe that justincely prototyped out to check that XDS_HOST is correctly set. This probe is on dashboard to make sure that the globals are correct (would be really hard to mess up) and also on data in case it is deployed standalone.
<br/><br/>
None
<br/><br/>
NA
<br/><br/>
4. Demonstrate the code …
=> Liveness probe to ensure XDS HOST is set correctly

gm-control-api/Chart.yaml, gm-control-api/json/edge/cluster.json, gm-control-api/json/edge/route-1.json, gm-control-api/json/edge/route-2.json, gm-control-api/json/edge/shared_rules.json, gm-control-api/json/services/cluster.json, gm-control-api/json/services/domain.json, gm-control-api/json/services/listener.json, gm-control-api/json/services/proxy.json, gm-control-api/json/services/route.json, gm-control-api/json/services/shared_rules.json, gm-control-api/json/special/cluster.json, gm-control-api/json/special/domain.json, gm-control-api/json/special/listener.json, gm-control-api/json/special/proxy.json, gm-control-api/json/special/route-catalog-to-internal-data-slash.json, gm-control-api/json/special/route-catalog-to-internal-data.json, gm-control-api/json/special/route-dashboard-slash.json, gm-control-api/json/special/route-data-jwt-slash.json, gm-control-api/json/special/route-data-jwt.json, gm-control-api/json/special/route-internal-data-jwt-slash.json, gm-control-api/json/special/route-internal-data-jwt.json, gm-control-api/json/special/route.json, gm-control-api/json/special/shared_rules.json, greymatter/Chart.yaml, greymatter/requirements.yaml
This PR fixes #514 and allows Helm to once again properly template the global zones for all of the mesh configurations.
none
none
I caught the error attempting to deploy in …
=> Adds the missing spaces in the global zone templating

greymatter/templates/sidecar-secret.yaml
This PR is in response to [this issue](https://github.com/DecipherNow/helm-charts/issues/488).  What was happening was that both `create_sidecar_secret` _and_ `mesh_tls.use_provided_certs` had to be false or else the sidecar secret would be created.  I removed the `mesh_tls.use_provided_certs` from the logic--I'm not sure why it was put there in the first place but I think it makes more sense without it.
<br/><br/>
2. What **changes to …
=> allows for the situation where the sidecar secret is already installed in the namespace

data/Chart.yaml, data/templates/data.yaml, greymatter/Chart.yaml, greymatter/requirements.yaml
Sets the timeout further into the future for data's liveness probe. Needed because openshift on devinabox takes awhile for sidecars to connect to gm-control. Note this liveness probe is only on dashboard and data. Dashboard happens to already have this initial delay value and as such did not need to change.
<br/><br/>
None
<br/><br/>
3. Have you documented any additional setup steps or configurations …
=> Pushing timeout back for devinabox openshift

Makefile, data/Makefile, edge/Makefile, global.yaml, sense/Makefile, spire/Makefile, spire/README.md
This PR adds a makefile for spire helm releases and updates the top level Makefile to install spire with the rest of the Grey Matter core components.
To test you can start up a k3d cluster and then run `make install`
=> add in spire makefile

fabric/values.yaml
Fixes extra quote @chrisbsmith found causing errors for sidecars in the fabric namespace
=> Fix fabric sidecar xds_port

secrets/Makefile
This PR simply prevents printing commands to the terminal when running `make credentials` such as the following:
```
(base)  dtillery@MacBook-Pro  ~/dev/workspace/decipher/gm/helm-charts   suppress-print  make credentials
if [ "helm-charts" == "helm-charts" ]; then \
./ci/scripts/build-credentials.sh; \
elif [ "helm-charts" == "secrets" ]; then \
./../ci/scripts/build-credentials.sh; \
else \
echo "Make sure you are running this from helm-charts or secrets makefile"; \
fi
decipher email:
```
=> don't print commands to terminal

docs/spire/configuration.md
The path to the SPIRE socket was plural instead of singular.
=> fix spire socket path in docs

fabric/control-api/json/services/listener.json, fabric/control-api/json/special/listener.json, fabric/control-api/values.yaml
Closes #580 
As you see in fabric/control-api/values.yaml, these were made configurable:
```
rbac:
admin:
header_name: user_dn
match_type: exact_match
header_value: CN=quickstart,OU=Engineering,O=Decipher Technology Studios,L=Alexandria,ST=Virginia,C=US
```
If user_dn needs to be overridden, you can add something like the following to global.yaml:
```
rbac:
admin:
header_value: new-value
```
How to test:
I removed lines for spire_volume_mount (control-api/templates/control-api.yaml) as it is to be dealt in another issue. But for references, the error looked like:
```
helm template fabric/control-api -f global.yaml --debug
install.go:158: [debug] Original chart version: ""
install.go:175: [debug] CHART PATH: /Users/hiromi/git/helm-charts/fabric/control-api
Error: template: …
```
=> User DN etc are now configurable

edge/templates/edge-ingress.yaml, edge/values.yaml
This eliminates the duplicate code described in issue #595 and also fixes the ingress code logic that prevented voyager from being used as an ingress
none
no additional documentation
- …
=> [release-2.2] fixes the logic for the edge ingress to use voyager

Makefile, docs/Deploy with K3d.md
Closes #588 
Added a question regarding whether or not to install spire. When you run `make install`, the only way spire will be installed is for you to type `y` - everything else is considered as no.
Also the change for `docs/Deploy with K3d.md` is removing a strange character:
=> If spire is disabled, the spire charts should not be installed 

Makefile
Updates the install-spire makefile target to use the `global.spire.enabled` value to determine if helm should install spire.
None
None needed
Change the `global.spire.enabled=true` and …
=> use global.yaml spire.enabled value to decide to install spire or not

Makefile
fixes `make credentials` mistake from my most recent PR updating the makefile
=> fix mistake from make credentials

docs/Generic Install.md, docs/install.md, global.yaml, secrets/values.yaml
this PR adds a doc for installing using the hosted helm charts and fixes the format for dockerCredentials in `secrets/values.yaml` .  I also added the global value control.additional_namespaces to the `global.yaml` file.
=> Adds doc for generic installation, fixes dockercreds format

fabric/control-api/json/special/listener.json
closes #672 
Properly enables the jwt_authn filter and fixes rbac config on edge to get email claim
None
To test:
Run `make install` and check the edge logs - you should see the following at startup to indicate that the jwt_authn filter is on:
```bash
[2020-07-02 14:12:18.714][9][info][jwt] [bazel-out/k8-fastbuild/bin/external/envoy/source/extensions/filters/http/jwt_authn/_virtual_includes/filter_con …
```
=> fix edge listener jwt rbac

data/gm-data/values.yaml, data/values.yaml, fabric/control-api/config/bootstrap.sh, fabric/control-api/json/special/internal-cluster-catalog-data-internal.json, fabric/control-api/json/special/internal-cluster-data-to-jwt-extdata.json, fabric/control-api/json/special/internal-cluster-int-data-to-int-jwt.json, fabric/control-api/json/special/route-catalog-to-internal-data-slash.json, fabric/control-api/json/special/route-catalog-to-internal-data.json, fabric/control-api/json/special/route-data-jwt-extdata.json, fabric/control-api/json/special/route-data-jwt-slash-extdata.json, fabric/control-api/json/special/route-int-data-int-jwt-slash.json, fabric/control-api/json/special/route-int-data-int-jwt.json, fabric/control-api/values.yaml, fabric/values.yaml, sense/values.yaml
<br/><br/>
closes #651 
This updates mesh configs and service env vars to use egress domains for internal routes in the non-spire install
<br/><br/>
None
Details:
This PR does a couple of things to update the egress routing:
- updates any service env vars making requests to other services in the mesh to go through their egress listener port (10909). These egress listeners/domains are [already created …
=> 651 egress

sense/catalog/templates/catalog-init-hook.yaml, sense/values.yaml
catalog-init job wasn't being created. I noticed that the image pull policy was missing, after adding it back the job was created and ran successfully. 
none
n/a
I installed on k3d and …
=> add missing ImagePullPolicy for catalog-init job

TLS_METRICS.md
@chrisbsmith, @moosecanswim , @justincely, @tilleryd, I've captured what i did to secure the grey matter metrics endpoint on catalog in the deployment kyle stood up for me.  note that this effectively breaks metrics scraping on all other services until they have the same mesh configurations and does not secure the envoy metrics but that pattern would be the same.
=> mtls-metrics documentation

data/gm-data/templates/_envvars.tpl, edge/templates/_envvars.tpl, fabric/control-api/templates/_envvars.tpl, fabric/jwt-gov/templates/_envvars.tpl, fabric/jwt/templates/_envvars.tpl, fabric/redis/templates/_envvars.tpl, sense/catalog/templates/_envvars.tpl, sense/dashboard/templates/_envvars.tpl, sense/slo/templates/_envvars.tpl
After upgrading helm to v3.3.4, I started to get the following error:
```
Error: template: fabric/charts/jwt/templates/jwt.yaml:51:12: executing "fabric/charts/jwt/templates/jwt.yaml" at <include "sidecar.envvars" .>: error calling include: template: fabric/charts/control-api/templates/_envvars.tpl:53:10: executing "sidecar.envvars" at <include "envvar" $args>: error calling include: template: fabric/charts/control-api/templates/_envvars.tpl:36:19: executing "envvar" at <(tpl $e.value $top) ne "">: can't give argument to non-function tpl $e.value $top
make[1]: *** [fabric] Error 1
make: *** [install] Error 2
```
Due to the comment above the if statement suggested of removal 7 months ago, rather than fixing the if statement, removing them all together.
Here is the version of my helm: …
=> Removing if statements

global.yaml
Provides clarity to users configuring this file.
Fixes spelling error in global.yaml for "kubernetes" (Was "kuberenetes").
No additional steps or configuration options are documented.
=> global.yaml spelling correction

.chart-testing/fabric-sense-data.yaml, .github/workflows/linter.yaml, charts/data/Chart.yaml, charts/edge/Chart.yaml, charts/fabric/Chart.yaml, charts/sense/Chart.yaml, charts/spire/Chart.yaml, data/Chart.yaml, data/gm-data/Chart.yaml, fabric/Chart.yaml, fabric/control-api/Chart.yaml, fabric/control/Chart.yaml, fabric/jwt-gov/Chart.yaml, fabric/jwt/Chart.yaml, fabric/redis/Chart.yaml, sense/Chart.yaml, sense/catalog/Chart.yaml, sense/dashboard/Chart.yaml, sense/slo/Chart.yaml, spire/Chart.yaml, spire/agent/Chart.yaml, spire/server/Chart.yaml
This PR gets the GitHub Actions Linter working as expected.  It still runs CircleCI for now and will continue to do so until we fully move to GitHub Actions for full CI/CD of the helm charts
=> Fix GitHub actions linter

.circleci/config.yml
The helm test job has started to fail when deploying sense and fabric. This PR increases the circleci machine resource size from medium to xlarge.  This _should_ allow the tests to pass.  I have verified that the test still complete successfully when run locally.
=> increase the circle resource size to allow helm tests to complete

.circleci/config.yml
One more fix for CircleCI.  The helm jobs were failing because I switched from environment variables to a Context and was not adding  the context to the greymatter-test job.
=> add context to helm test job

data/Chart.yaml, data/gm-data/templates/_helpers.tpl, docs/Ingress.md, edge/Chart.yaml, edge/templates/edge-service.yaml, edge/values.yaml, fabric/control-api/templates/control-api-service.yaml, sense/catalog/Chart.yaml, sense/catalog/templates/catalog-service.yaml
3 changes here:
- the mongo svc change.  This allows data to resolve mongo in both GKE and EKS (tested both)
- added a template value for the edge svc type.  This allows dev to still auto provision an ingress point.  I'll update the docs accordingly if this gets merged.
- to test this, install the edge chart with a loadbalancer: `helm install edge edge --set=global.environment=eks --set=edge.ingress.type=LoadBalancer -f global.yaml` and it'll function as the docs say they do [here](https://docs.greymatter.io/guides/installation-kubernetes#5-accessing-the-dashboard)
- minor, seemingly irrelevant modification to the catalog svc to make it match control-api.  For some reason it didn't work as it was in GKE, now it is fine.
=> remove pod name from mongodb SVC

.circleci/config.yml, .github/workflows/helm-test.yaml, ci/scripts/k3d.sh
set k3d version tag to 3.1.4 following an issue with spire & k3d 3.1.4+. Also adds to the `make k3d` script with this information
see #773
=> k3d version check < 3.1.4

docs/Getting Started.md
Fixed a spelling issue in the Getting Started documentation on release-2.2 branch to address issue #724.
=> Fixed spelling issue (#724)

.github/workflows/release.yaml
Fixes an error releasing the fabric gov charts.  I used https://github.com/nektos/act to find my error.
=> Add the missing -e to release jwt gov charts

data/Makefile, fabric/Makefile, sense/Makefile, spire/Makefile
Issue #626 
Redirected the error stream for the `kubectl get sa waiter-sa` call to `/dev/null`. Also removed some extraneous echo statements.
=> Removed waiter-sa error from makefiles (#626)

data/Chart.yaml, data/gm-data/Chart.yaml, data/gm-data/values.yaml, data/values.yaml, docs/Service Accounts.md, fabric/Chart.yaml, fabric/control-api/Chart.yaml, fabric/control-api/values.yaml, fabric/control/Chart.yaml, fabric/control/values.yaml, fabric/values.yaml, global.yaml, sense/Chart.yaml, sense/catalog/Chart.yaml, sense/catalog/values.yaml, sense/slo/Chart.yaml, sense/slo/values.yaml, sense/values.yaml
for ISSUE#793
uses the waiter image in greymatter.io repo instead of deciphernow dockerhub
several of the values files changed and the parent values files along with them and the global.yaml to point to the correct image repo
none needed. …
=> point waiter images to the new greymatter.io docker repo

ci/scripts/credentials.template
There may be a time when a user has a password that starts with a special character. If this is the case, the make secrets command will error with the following error:
cd secrets && make secrets
cp ../credentials.yaml .
rds.enabled in secrets/values.yaml and sense/values.yaml match
helm install secrets . -f credentials.yaml -f ../global.yaml
Error: failed to parse credentials.yaml: error converting YAML to JSON: yaml: line 5: found character that cannot start any token
make[1]: *** [secrets] Error 1
make: *** [secrets] Error 2
The YAML failure is with the special character. This PR just puts quotes around the password to ensure that any password will be accepted.
I'll push a PR against release-2.2 also.
=> add quotes to the password

ci/scripts/credentials.template
There may be a time when a user has a password that starts with a special character. If this is the case, the make secrets command will error with the following error:
cd secrets && make secrets
cp ../credentials.yaml .
rds.enabled in secrets/values.yaml and sense/values.yaml match
helm install secrets . -f credentials.yaml -f ../global.yaml
Error: failed to parse credentials.yaml: error converting YAML to JSON: yaml: line 5: found character that cannot start any token
make[1]: *** [secrets] Error 1
make: *** [secrets] Error 2
The YAML failure is with the special character. This PR just puts quotes around the password to ensure that any password will be accepted.
I'll push a PR against release-2.2 also.
=> add quotes to the credentials password template

sense/Chart.yaml, sense/catalog/Chart.yaml, sense/catalog/values.yaml, sense/values.yaml
This fixes the reference to Catalog's database index when configured to use an external Redis provider. I had originally duplicated Catalog API's database index (`control_api_db`), which caused Catalog and Control API to share the same database.
=> Use catalog_db value for external-redis

fabric/Chart.yaml, fabric/control-api/Chart.yaml, fabric/control-api/values.yaml, fabric/values.yaml, sense/Chart.yaml, sense/catalog/Chart.yaml, sense/catalog/values.yaml, sense/values.yaml
resolves https://github.com/greymatter-io/helm-charts/issues/811
- Sets enable_inline_docs true
- Updates services that did not have apiSpecEndpoint/documentation set
to test:
- `make k3d install`
- Check the dashboard and see that all core services besides edge and dashboard are rendering inline docs
=> display inline docs

data/Chart.yaml, data/gm-data/Chart.yaml, data/gm-data/values.yaml, data/values.yaml, docs/Upgrading Sidecar Metrics to mTLS.md, edge/Chart.yaml, edge/values.yaml, fabric/Chart.yaml, fabric/control-api/Chart.yaml, fabric/control-api/values.yaml, fabric/control/Chart.yaml, fabric/control/values.yaml, fabric/jwt-gov/Chart.yaml, fabric/jwt-gov/values.yaml, fabric/jwt/Chart.yaml, fabric/jwt/values.yaml, fabric/values.yaml, proxy/Chart.yaml, proxy/values.yaml, sense/Chart.yaml, sense/catalog/Chart.yaml, sense/catalog/values.yaml, sense/dashboard/Chart.yaml, sense/dashboard/values.yaml, sense/slo/Chart.yaml, sense/slo/values.yaml, sense/values.yaml
This PR updates the Docker images to use the 1.3 release candidates detailed at: https://docs.greymatter.io/v/1.3-beta/release_notes. The ClickUp ticket for this is: https://app.clickup.com/t/gyuz1z
Tested the changes as a fresh install to a new EKS 1.17 cluster and everything looks good.
All pods running without issue:
```bash
[mike@orion:~/Code/release-testing]$ kc get pod
NAME                           READY   STATUS      RESTARTS   AGE
catalog-75d4c66477-5nplq       2/2     Running     0          62m
catalog-init-2fztm             0/1     Completed   0          62m
control-7cc5f658b-mg9ck        1/1     Running     0          64m
control-api-0                  2/2     Running     0          64m
control-api-init-8c27g         0/1     Completed   0          64m …
```
=> Updated to use the 1.3 release candidate images

fabric/Chart.yaml, fabric/control-api/Chart.yaml, fabric/control-api/values.yaml, fabric/values.yaml, sense/Chart.yaml, sense/catalog/Chart.yaml, sense/catalog/values.yaml, sense/values.yaml
1. the apiEndpoints for each service card has "localhost" with the default charts.  this breaks the clickthrough functionality when deploying remotely.  This can just be changed to relative paths so it works in all cases.  
<br/><br/>
2. No changes needed
<br/><br/>
no
<br/><br/>
<br/><br/>
=> use relative paths for apiEndpoints

README.md
This change allows copying and pasting the helm commands in one go, and matches the style of the rest of the README.
=> Make it easier to copy and paste commands

fabric/Chart.yaml, fabric/control-api/Chart.yaml, fabric/control-api/json/special/listener-egress.json, fabric/control-api/json/special/listener.json
closes https://github.com/greymatter-io/helm-charts/issues/843
- remove edge egress domain from edge listener
- remove edge domain from edge egress listener
<br/><br/>
none
<br/><br/>
n/a
<br/><br/>
4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull …
=> removed extra domains from edge and edge-egress listeners

.github/workflows/release.yaml
This adds another step for the github action to run which will release the spire server and agent chart
=> publish the server and agent helm charts

.github/workflows/release.yaml
Switch the spire release with the greymatter release to force publish.  The release will fail on greymatter but thats ok since those charts are already published.
=> Publish spire server agent

.chart-testing/fabric-sense-data.yaml, .github/workflows/helm-test.yaml, fabric/control-api/Chart.yaml
This PR fixes the umbrella chart linting.  It adjusts two things:
* installs helm and runs a `helm dep up` for the umbrella charts
* updates the umbrella config file 
You can see a successful capture of the need to update an umbrella chart here: https://github.com/greymatter-io/helm-charts/runs/1750370868?check_suite_focus=true
And then a successful run of the linter, https://github.com/greymatter-io/helm-charts/actions/runs/504268990
closes #854
=> Update the linters to catch when an umbrella chart needs to be updated

fabric/Chart.yaml, fabric/control-api/Chart.yaml, fabric/control-api/values.yaml
…otations is a table. Ignoring non-table value' warning
fixes issue which chart that caused this warning to apear: 'destination for annotations is a table. Ignoring non-table value'
none
none
4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request …
=> fix fabric warning 2.3

fabric/Chart.yaml, fabric/control-api/Chart.yaml, fabric/control-api/values.yaml
…otations is a table. Ignoring non-table value' warning
'destination for annotations is a table. Ignoring non-table value' error when running helm install / template fabric
none
none needed
4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes …
=> fix fabric warning 2.4

.github/workflows/release.yaml
points the gitbook sync to the 1.3 branch
=> point the working target branch to 1.3

.github/gitbook-sync-action-readme.md, .github/workflows/helm-test.yaml, .github/workflows/linter.yaml, .github/workflows/release.yaml
brings the same gitbook sync from release-2.3 to release-2.4 but points the target branch to `1.4-beta`
=> add gitbook sync workflow to 2.4

.chart-testing/services.yaml, .github/workflows/helm-test.yaml, Makefile, README.md, data/Makefile, edge/.helmignore, edge/Chart.yaml, edge/Makefile, fabric/.helmignore, fabric/Chart.yaml, fabric/Makefile, global.yaml, helpers.mk, secrets/.helmignore, secrets/Chart.yaml, secrets/Makefile, secrets/templates/mesh-identity.yaml, secrets/values.yaml, sense/.helmignore, sense/Chart.yaml, sense/Makefile, spire/.helmignore, spire/Chart.yaml, spire/Makefile
updates the helm release names that the make files use.
**This has a change to global.yaml**.  a customer field has been added under global.releases.  This is used to create the helm release name as well as an identifier inside a mesh config.
to test install the mesh from the makefiles like normal `make secrets && make install`
do a `helm ls` and you will see all the regular releases in the form `<chart>-<customer>-<random number>`
You should be able to hit the endpoint as you normally do.
To test that the configmap can protect the mesh:
> (if you changed the customer value then replace "development" with that name)
First copy the configmap so we can easily restore it:
`kc get configmap greymatter-mesh-identity-development -o yaml > mesh-identity.yaml`
Now delete that configmap
`kc delete …
=> Helm release names

fabric/Chart.yaml, fabric/control-api/templates/control-api.yaml
Closes #910 
When `globals.environment` is set to `openshift`, control api should not add the securityContext.  This adds an `if check` around the securityContext and does not add it when configured for openshift
None
Nothing new here …
=> don't template controlAPI securityContext for openshift

global.yaml, secrets/Chart.yaml, secrets/templates/_cert-helper.tpl
When set to auto create the edge ingress certs, it would always create the edge cert with `.Values.global.route_url_name`, and if that value didn't exist it would add an error value to the DN.  This adds a check to the cert creation to check for the value. 
This was only seen on local dev instances where no route_url_name was set.
Closes #921 
2. What **changes to global.yaml** are required?
This PR adds the `route_url_name` to the globals.yaml …
=> set edge ingress DN properly

data/Chart.yaml, data/gm-data/Chart.yaml, data/gm-data/templates/mongo.yaml, fabric/Chart.yaml, fabric/jwt-gov/Chart.yaml, fabric/jwt-gov/templates/redis.yaml, fabric/jwt-gov/values.yaml, fabric/jwt/Chart.yaml, fabric/jwt/templates/redis.yaml, fabric/jwt/values.yaml, fabric/redis/Chart.yaml, fabric/redis/templates/redis.yaml, fabric/redis/values.yaml, test/greymatter_integration_test.go
This PR does a few things:
* Updates the version of redis we use for mesh-redis and jwt-redis
* Allows users to specify commands and args for redis rather than having them hard coded in the POD yaml
* Fixes a bug with the Data Mongo instance to remove securityContext if running OpenShift
None
No additional Options
4. …
=> Update the Redis pods to allow commands and arguments to be provided in the values.yaml

secrets/Chart.yaml, secrets/templates/global-certs-secret.yaml, secrets/templates/sidecar-secret.yaml
When `global.global_certs.enabled` is set to true, the `sidecar-certs` should match the values provided for the `global_certs`. This fixes that.
none
none needed
Helm templates verify …
=> If global certs enabled, sidecar-certs should match

edge/Chart.yaml, edge/templates/edge-ingress.yaml, edge/templates/edge-service.yaml, edge/templates/edge.yaml, edge/values.yaml
The Grey Matter edge chart is one that can be reused in scenarios where we want to add an Edge node to a specific service. As it stands, the edge name is hard coded so it will never work.  We need to allow the edge name to be templated.
n/a
n/a
4. Demonstrate the code is solid. Example: The exact commands you ran and their …
=> Allow the Edge Name to be templated

spire/Chart.yaml, spire/agent/Chart.yaml, spire/server/Chart.yaml
Bumps the spire chart versions in an attempt to have them redeploy properly to the helm repo
=> bump spire chart versions

edge/Chart.yaml, edge/templates/_domain.tpl, edge/templates/edge-ingress.yaml, edge/values.yaml
fixes #932
The existing code doesn't template the proper <route>.<domain> when building the Nginx ingress object. The code now uses the same `domain` template as the OCP route object.
None
No other steps needed.
4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if …
=> Template the domain for an ingress object the same as an OCP route object

edge/Chart.yaml
the 3.0.7 did not release failed to release using cr 1.2.1
we reverted to cr 1.0.0 however that did not release because it did not detect a change in the edge chart.
incrementing the chart.yaml version to 3.0.8 to force a re release
<br/><br/>
<br/><br/>
<br/><br/>
4. Demonstrate the code is solid. Example: The exact …
=> Increment edge chart.yaml to kick new release
